-- MySQL Script generated by MySQL Workbench
-- Wed May 13 11:29:43 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `correo` VARCHAR(60) NOT NULL,
  `tipo_identificacion` VARCHAR(10) NOT NULL,
  `numero_identificacion` VARCHAR(12) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `alias_usuario` VARCHAR(45) NOT NULL,
  `password` VARCHAR(225) NOT NULL,
  `fecha_registro` DATETIME NOT NULL,
  `estado_cuenta` TINYINT(1) NOT NULL DEFAULT 1,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `correo_UNIQUE` (`correo` ASC) VISIBLE,
  UNIQUE INDEX `numero_identificacion_UNIQUE` (`numero_identificacion` ASC) VISIBLE,
  UNIQUE INDEX `alias_usuario_UNIQUE` (`alias_usuario` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`tipo_turismo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo_turismo` (
  `id_tipo_turismo` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_tipo_turismo`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horarios_preferidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horarios_preferidos` (
  `id_horarios_preferidos` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_horarios_preferidos`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`presupuestos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`presupuestos` (
  `id_presupuesto` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `valor_minimo` DECIMAL(10,2) NOT NULL,
  `valor_maximo` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_presupuesto`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`caracterizacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`caracterizacion` (
  `id_caracterizacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `avatar` VARCHAR(255) NOT NULL,
  `tiempo_disponible` VARCHAR(45) NOT NULL,
  `sexo` VARCHAR(45) NOT NULL,
  `id_tipo_turismo` INT NOT NULL,
  `id_horarios_preferidos` INT NOT NULL,
  `id_presupuesto` INT NOT NULL,
  PRIMARY KEY (`id_caracterizacion`),
  INDEX `fk_caracterizacion_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_caracterizacion_tipoturismo_idx` (`id_tipo_turismo` ASC) VISIBLE,
  INDEX `fk_caracterizacion_horarios_preferidos_idx` (`id_horarios_preferidos` ASC) VISIBLE,
  INDEX `fk_caracterizacion_presupuesto_idx` (`id_presupuesto` ASC) VISIBLE,
  CONSTRAINT `fk_caracterizacion_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_caracterizacion_tipoturismo`
    FOREIGN KEY (`id_tipo_turismo`)
    REFERENCES `mydb`.`tipo_turismo` (`id_tipo_turismo`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_caracterizacion_horarios_preferidos`
    FOREIGN KEY (`id_horarios_preferidos`)
    REFERENCES `mydb`.`horarios_preferidos` (`id_horarios_preferidos`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_caracterizacion_presupuesto`
    FOREIGN KEY (`id_presupuesto`)
    REFERENCES `mydb`.`presupuestos` (`id_presupuesto`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugares` (
  `id_lugar` INT NOT NULL AUTO_INCREMENT,
  `nombre_lugar` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `latitud` DECIMAL(10,8) NOT NULL,
  `longitud` DECIMAL(11,8) NOT NULL,
  `imagen_url` VARCHAR(255) NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `horario` VARCHAR(100) NULL,
  `costo` DECIMAL(10,2) NULL,
  `contacto` VARCHAR(20) NULL,
  `sitio_web` VARCHAR(255) NULL,
  `seguridad` TINYINT NOT NULL,
  `tiempo_aproximado` INT NULL,
  PRIMARY KEY (`id_lugar`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`comentarios` (
  `id_comentarios` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_lugar` INT NOT NULL,
  `comentarios` TEXT NOT NULL,
  `fecha_comentario` DATETIME NOT NULL,
  `puntuacion` INT NOT NULL,
  PRIMARY KEY (`id_comentarios`),
  INDEX `fk_comentarios_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_comentarios_lugar_idx` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_comentarios_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_comentarios_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hobbies`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hobbies` (
  `id_hobbies` INT NOT NULL,
  `nombre_hobbie` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_hobbies`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`hobbies_usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`hobbies_usuario` (
  `id_hobbies_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_hobbie` INT NOT NULL,
  PRIMARY KEY (`id_hobbies_usuario`),
  INDEX `fk_usuariohobbie_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_usuariohobbie_hobbie_idx` (`id_hobbie` ASC) VISIBLE,
  CONSTRAINT `fk_usuariohobbie_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuariohobbie_hobbie`
    FOREIGN KEY (`id_hobbie`)
    REFERENCES `mydb`.`hobbies` (`id_hobbies`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`favoritos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`favoritos` (
  `id_favoritos` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_lugar` INT NOT NULL,
  `fecha_agregado` DATETIME NOT NULL,
  PRIMARY KEY (`id_favoritos`),
  INDEX `fk_favorito_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_favorito_lugar_idx` (`id_lugar` ASC) VISIBLE,
  UNIQUE INDEX `uq_usuario_lugar` (`id_usuario` ASC, `id_lugar` ASC) INVISIBLE,
  CONSTRAINT `fk_favorito_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_favorito_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`bitacora` (
  `id_bitacora` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_lugar` INT NOT NULL,
  `fecha_visita` DATETIME NOT NULL,
  PRIMARY KEY (`id_bitacora`),
  INDEX `fk_guardados_usuario_idx` (`id_usuario` ASC) VISIBLE,
  INDEX `fk_guardados_lugares_idx` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_bitacora_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_bitacora_lugares`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rutas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rutas` (
  `id_rutas` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `nombre_ruta` VARCHAR(100) NOT NULL,
  `fecha_creacion` DATETIME NOT NULL,
  `tipo` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_rutas`),
  INDEX `fk_ruta_usuario_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_ruta_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `mydb`.`usuarios` (`id_usuario`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ruta_lugares`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ruta_lugares` (
  `id_ruta_lugares` INT NOT NULL AUTO_INCREMENT,
  `id_rutas` INT NOT NULL,
  `id_lugar` INT NOT NULL,
  `orden_secuencial` INT NOT NULL,
  `tiempo_estimado` INT NOT NULL,
  PRIMARY KEY (`id_ruta_lugares`),
  INDEX `fk_rutalugar_ruta_idx` (`id_rutas` ASC) VISIBLE,
  INDEX `fk_rutalugar_lugares_idx` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_rutalugar_rutas`
    FOREIGN KEY (`id_rutas`)
    REFERENCES `mydb`.`rutas` (`id_rutas`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rutalugar_lugares`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`eventos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`eventos` (
  `id_eventos` INT NOT NULL AUTO_INCREMENT,
  `nombre_evento` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NOT NULL,
  `fecha_evento` DATETIME NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `id_lugar` INT NOT NULL,
  PRIMARY KEY (`id_eventos`),
  INDEX `fk_evento_lugar_idx` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_evento_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`lugar_imagen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`lugar_imagen` (
  `id_lugar_imagen` INT NOT NULL AUTO_INCREMENT,
  `id_lugar` INT NOT NULL,
  `url_imagen` VARCHAR(255) NOT NULL,
  `descripcion` VARCHAR(100) NULL,
  `principal` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id_lugar_imagen`),
  INDEX `fk_imagen_lugar_idx` (`id_lugar` ASC) VISIBLE,
  CONSTRAINT `fk_imagen_lugar`
    FOREIGN KEY (`id_lugar`)
    REFERENCES `mydb`.`lugares` (`id_lugar`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
